create table property
(
    id             bigint generated by default as identity
        primary key,
    application    varchar(255),
    label          varchar(255),
    profile        varchar(255),
    property_key   varchar(255) not null,
    property_value varchar(500)
);

INSERT INTO property (application, profile, label, property_key, property_value)
VALUES ('my_client_app','dev','main','configA','Config A');
INSERT INTO property (application, profile, label, property_key, property_value)
VALUES ('my_client_app','dev','main','configB','Config B - Dev');
INSERT INTO property (application, profile, label, property_key, property_value)
VALUES ('my_client_app','dev','main','spring.data.mongodb.database','myDbName');
INSERT INTO property (application, profile, label, property_key, property_value)
VALUES ('my_client_app','dev','main','spring.data.mongodb.host','localhost');
INSERT INTO property (application, profile, label, property_key, property_value)
VALUES ('my_client_app','dev','main','spring.data.mongodb.port','27017');

INSERT INTO property (application, profile, label, property_key, property_value)
VALUES ('my_client_app','dev','previous','configA','Config A');
INSERT INTO property (application, profile, label, property_key, property_value)
VALUES ('my_client_app','dev','previous','configB','Config B - Dev');
INSERT INTO property (application, profile, label, property_key, property_value)
VALUES ('my_client_app','dev','previous','spring.data.mongodb.database','myDbName');
INSERT INTO property (application, profile, label, property_key, property_value)
VALUES ('my_client_app','dev','previous','spring.data.mongodb.host','localhost');
INSERT INTO property (application, profile, label, property_key, property_value)
VALUES ('my_client_app','dev','previous','spring.data.mongodb.port','27017');